version: 2
jobs:
  yarn_install:
    docker:
      - image: cimg/node:16.13.1

    steps:
      - checkout
      - restore_cache:
          name: Restore node_modules from cache
          key: yarn-dependencies-v1-{{ checksum "yarn.lock" }}

      - run: sudo yarn install

      - save_cache:
          paths:
            - node_modules
          name: Cache node_modules
          key: yarn-dependencies-v1-{{ checksum "yarn.lock" }}

  lint_docs:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - restore_cache:
          name: Restore node_modules from cache
          key: yarn-dependencies-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Check to make sure documentation coverage has improved
          command: npm run lint:docs

  eslint:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - restore_cache:
          name: Restore node_modules from cache
          key: yarn-dependencies-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Run Eslint
          command: node_modules/.bin/eslint src spec

  jest:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - restore_cache:
          name: Restore node_modules from cache
          key: yarn-dependencies-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Run Jest
          command: node_modules/.bin/jest spec

  verify_docs:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - restore_cache:
          name: Restore node_modules from cache
          key: yarn-dependencies-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Check to make sure docs are in correct format
          command: npm run lint:docs
      - run:
          name: Build docs
          command: yarn docs
      # TODO: Reenable when jsdoc doesn't change div ids
      # - run:
      #     name: Verify docs up-to-date
      #     command: git diff --exit-code ./docs

workflows:
  version: 2
  run_tests:
    jobs:
      - yarn_install
      - eslint:
          requires:
            - yarn_install
      - jest:
          requires:
            - yarn_install
      - verify_docs:
          requires:
            - yarn_install
