version: 2
jobs:
  yarn_install:
    docker:
      - image: circleci/node:12.18.4

    steps:
      - checkout
      - restore_cache:
          name: Restore node_modules from cache
          key: yarn-dependencies-v1-{{ checksum "package.json" }}

      - run: sudo yarn install

      - save_cache:
          paths:
            - node_modules
          name: Cache node_modules
          key: yarn-dependencies-v1-{{ checksum "package.json" }}

  yuidoc:
    docker:
      - image: circleci/node:12.18.4
    steps:
      - checkout
      - run:
          name: Check Javascript Docs
          command: sudo npm install -g yuidocjs && yuidoc --lint

  eslint:
    docker:
      - image: circleci/node:12.18.4
    steps:
      - checkout
      - restore_cache:
          name: Restore node_modules from cache
          key: yarn-dependencies-v1-{{ checksum "package.json" }}
      - run:
          name: Run Eslint
          command: node_modules/.bin/eslint src spec

  jest:
    docker:
      - image: circleci/node:12.18.4
    steps:
      - checkout
      - restore_cache:
          name: Restore node_modules from cache
          key: yarn-dependencies-v1-{{ checksum "package.json" }}
      - run:
          name: Run Jest
          command: node_modules/.bin/jest spec

  verify_docs:
    docker:
      - image: circleci/node:12.18.4
    steps:
      - checkout
      - restore_cache:
          name: Restore node_modules from cache
          key: yarn-dependencies-v1-{{ checksum "package.json" }}
      - run:
          name: Build docs
          command: yarn doc
      - run:
          name: Verify docs up-to-date
          command: git diff --exit-code ./docs

  verify_build:
    docker:
      - image: circleci/node:12.18.4
    steps:
      - checkout
      - restore_cache:
          name: Restore node_modules from cache
          key: yarn-dependencies-v1-{{ checksum "package.json" }}
      - run:
          name: Build
          command: yarn build
      - run:
          name: Verify build up-to-date
          command: git diff --exit-code ./dist

workflows:
  version: 2
  run_tests:
    jobs:
      - yarn_install
      - yuidoc
      - eslint:
          requires:
            - yarn_install
      - jest:
          requires:
            - yarn_install
      - verify_docs:
          requires:
            - yarn_install
      - verify_build:
          requires:
            - yarn_install
